### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HonoEagle** [ps-dps/MobCaptains#26] opened 2023-12-26 08:12 UTC
i always get this when i start my server

[08:10:10] [Worker-Main-1/ERROR]: Couldn't parse element loot_tables:ps-mob:base/uncommon - Not a json array: {"function":"minecraft:set_name","name":{"text":"Apocalypse","color":"dark_red","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Bulletproof Vest","color":"gray","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Diving Helmet","color":"aqua","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Winter Flippers","color":"blue","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Soul Stepper","color":"dark_aqua","italic":"false","bold":"true"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"S.W.A.T. Pants","color":"dark_gray","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Long Fall Boots","color":"aqua","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Tough Horse Armor","color":"white","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"S.W.A.T. Vest","color":"dark_gray","italic":"false"}}
[08:10:10] [Worker-Main-1/ERROR]: Couldn't parse element loot_tables:ps-mob:base/common - Not a json array: {"function":"minecraft:set_name","name":{"text":"Primitive Mining Drill","color":"dark_gray","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Primitive Chainsaw","color":"dark_gray","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Mjölnir","color":"yellow","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Multiplier","color":"white","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Match","color":"red","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Cactus","color":"dark_green","italic":"false","bold":"true"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Propeller Hat","color":"green","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Greed","color":"gold","italic":"false","bold":"true"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Knockback Stick","color":"gold","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Riot Shield","color":"dark_gray","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Medkit","color":"light_purple","italic":"false"}}
[08:10:10] [Worker-Main-1/ERROR]: Couldn't parse element loot_tables:ps-mob:base/legendary - Not a json array: {"function":"minecraft:set_name","name":{"text":"Robin's Bow","color":"dark_purple","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Immortal","color":"gold","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Plated Elytra","color":"dark_gray","italic":"false"}}
[08:10:10] [Worker-Main-1/ERROR]: Couldn't parse element loot_tables:ps-mob:base/rare - Not a json array: {"function":"minecraft:set_name","name":{"text":"YOLO","color":"dark_red","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Cornucopia","color":"gold","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Poseidon's Trident","color":"dark_aqua","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Reaper's Scythe","color":"black","italic":"false","bold":"true"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Lucky Charm","color":"dark_green","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Ripper","color":"dark_aqua","italic":"false"}}

**Comment by PuckiSilver** [comment] 2023-12-26 16:18
I can't reproduce this error in vanilla single player, the logs stay quiet, they don't even mention the data pack

What server are you using? Fabric? Paper? Vanilla?
Does the data pack not work because of this or does it just annoy you that it comes up?
What minecraft version are you using?`
Please provide more info or I will close this as invalid

**Comment by HonoEagle** [comment] 2023-12-27 11:21
yes sorry i forget that
Fabric 1.20.4 server

mob spawn but when i kill it, nothing drop

i use this onne : https://modrinth.com/datapack/mob-captains/version/v2.1.2+mod

**Comment by PuckiSilver** [comment] 2023-12-27 11:30
Do you have any other mods installed? Ones that could mess with this?

**Comment by taegyu42** [comment] 2023-12-29 04:59
I seem to have the same error when I make a 1.20.4 fabric server with this datapack.

[13:55:42] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[13:55:43] [ServerMain/INFO]: Found new data pack file/MobCaptains-v2.1.2.zip, loading it automatically
[13:55:43] [Worker-Main-8/ERROR]: Couldn't parse element loot_tables:ps-mob:base/uncommon - Not a json array: {"function":"minecraft:set_name","name":{"text":"Apocalypse","color":"dark_red","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Bulletproof Vest","color":"gray","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Diving Helmet","color":"aqua","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Winter Flippers","color":"blue","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Soul Stepper","color":"dark_aqua","italic":"false","bold":"true"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"S.W.A.T. Pants","color":"dark_gray","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Long Fall Boots","color":"aqua","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Tough Horse Armor","color":"white","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"S.W.A.T. Vest","color":"dark_gray","italic":"false"}}
[13:55:43] [Worker-Main-8/ERROR]: Couldn't parse element loot_tables:ps-mob:base/common - Not a json array: {"function":"minecraft:set_name","name":{"text":"Primitive Mining Drill","color":"dark_gray","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Primitive Chainsaw","color":"dark_gray","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Mjölnir","color":"yellow","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Multiplier","color":"white","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Match","color":"red","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Cactus","color":"dark_green","italic":"false","bold":"true"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Propeller Hat","color":"green","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Greed","color":"gold","italic":"false","bold":"true"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Knockback Stick","color":"gold","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Riot Shield","color":"dark_gray","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Medkit","color":"light_purple","italic":"false"}}
[13:55:43] [Worker-Main-8/ERROR]: Couldn't parse element loot_tables:ps-mob:base/legendary - Not a json array: {"function":"minecraft:set_name","name":{"text":"Robin's Bow","color":"dark_purple","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Immortal","color":"gold","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Plated Elytra","color":"dark_gray","italic":"false"}}
[13:55:43] [Worker-Main-8/ERROR]: Couldn't parse element loot_tables:ps-mob:base/rare - Not a json array: {"function":"minecraft:set_name","name":{"text":"YOLO","color":"dark_red","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Cornucopia","color":"gold","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Poseidon's Trident","color":"dark_aqua","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Reaper's Scythe","color":"black","italic":"false","bold":"true"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Lucky Charm","color":"dark_green","italic":"false"}}; Not a json array: {"function":"minecraft:set_name","name":{"text":"Ripper","color":"dark_aqua","italic":"false"}}
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/rare}.pools[0].entries[0]: Unknown loot table called ps-mob:base/common
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/rare}.pools[0].entries[1]: Unknown loot table called ps-mob:base/uncommon
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/common}.pools[0].entries[3]: Unknown loot table called ps-mob:base/legendary
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/rare}.pools[0].entries[2]: Unknown loot table called ps-mob:base/rare
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/common}.pools[0].entries[2]: Unknown loot table called ps-mob:base/rare
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/rare}.pools[0].entries[3]: Unknown loot table called ps-mob:base/legendary
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/common}.pools[0].entries[1]: Unknown loot table called ps-mob:base/uncommon
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/common}.pools[0].entries[0]: Unknown loot table called ps-mob:base/common
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/legendary}.pools[0].entries[1]: Unknown loot table called ps-mob:base/uncommon
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/legendary}.pools[0].entries[0]: Unknown loot table called ps-mob:base/common
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/legendary}.pools[0].entries[3]: Unknown loot table called ps-mob:base/legendary
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/legendary}.pools[0].entries[2]: Unknown loot table called ps-mob:base/rare
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/uncommon}.pools[0].entries[1]: Unknown loot table called ps-mob:base/uncommon
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/uncommon}.pools[0].entries[2]: Unknown loot table called ps-mob:base/rare
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/uncommon}.pools[0].entries[0]: Unknown loot table called ps-mob:base/common
[13:55:43] [ServerMain/WARN]: Found loot table element validation problem in {loot_tables:ps-mob:captain/uncommon}.pools[0].entries[3]: Unknown loot table called ps-mob:base/legendary
[13:55:44] [ServerMain/INFO]: Loaded 7 recipes
[13:55:44] [ServerMain/ERROR]: Failed to load function ps-mob:config
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 2: Invalid chat component: Not a JSON object: ["",{"text":"\n"},{"text":"M","color":"white"},{"text":"o","color":"#FF0000"},{"text":"b C","color":"white"},{"text":"a","color":"#FF0000"},{"text":"ptains ","color":"white"},{"text":"Config","color":"gold"},{"text":"\n"},{"text":"Cool down ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .cool_down ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"The time, in seconds, to stop trying to spawn a captain after successfully spawning one"}},{"text":"[0 to 2147483647]","color":"gray"},{"text":" "},{"score":{"name":".cool_down","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Spawn chance ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .spawn_chance ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"The maximum chance, that a mob becomes a Mob Captain, with 1 being 0.1% and 1000 being 100%"}},{"text":"[0 - 1000]","color":"gray"},{"text":" "},{"score":{"name":".spawn_chance","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Notify on spawn ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .notify_on_spawn ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"What rarity of Mob Captain is announced to chat, with 0 being for none, 1 only for legendaries and 4 being for all rarities of Mob Captain"}},{"text":"[0 - 4]","color":"gray"},{"text":" "},{"score":{"name":".notify_on_spawn","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Notify with sound ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .notify_with_sound ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"If a Mob Captain is announced to chat, a sound to all nearby players will play, with 0 being disabled and 1 being enabled"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".notify_with_sound","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Should glow ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .should_glow ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"If a Mob Captain's silhouette should show through blocks, with 0 being disabled and 1 being enabled"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".should_glow","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Beam on spawn ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .beam_on_spawn ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"If Mob Captains should create a particle beam when spawning that shows their location for about 1 second, with 1 being turned on and 0 it being turned off"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".beam_on_spawn","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Weight common ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .weight_common ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"Weight for a Mob Captain being of common rarity"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".weight_common","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Weight uncommon ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .weight_uncommon ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"Weight for a Mob Captain being of uncommon rarity"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".weight_uncommon","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Weight rare ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .weight_rare ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"Weight for a Mob Captain being of rare rarity"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".weight_rare","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Weight legendary ","clickEvent":{"action":"suggest_legendary","value":"/scoreboard players set .weight_legendary ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"Weight for a Mob Captain being of legendary rarity"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".weight_legendary","objective":"ps-mob.config"},"color":"red"},{"text":"\n"}] at position 4644: ...t": "\n"}]<--[HERE]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 2: Invalid chat component: Not a JSON object: ["",{"text":"\n"},{"text":"M","color":"white"},{"text":"o","color":"#FF0000"},{"text":"b C","color":"white"},{"text":"a","color":"#FF0000"},{"text":"ptains ","color":"white"},{"text":"Config","color":"gold"},{"text":"\n"},{"text":"Cool down ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .cool_down ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"The time, in seconds, to stop trying to spawn a captain after successfully spawning one"}},{"text":"[0 to 2147483647]","color":"gray"},{"text":" "},{"score":{"name":".cool_down","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Spawn chance ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .spawn_chance ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"The maximum chance, that a mob becomes a Mob Captain, with 1 being 0.1% and 1000 being 100%"}},{"text":"[0 - 1000]","color":"gray"},{"text":" "},{"score":{"name":".spawn_chance","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Notify on spawn ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .notify_on_spawn ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"What rarity of Mob Captain is announced to chat, with 0 being for none, 1 only for legendaries and 4 being for all rarities of Mob Captain"}},{"text":"[0 - 4]","color":"gray"},{"text":" "},{"score":{"name":".notify_on_spawn","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Notify with sound ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .notify_with_sound ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"If a Mob Captain is announced to chat, a sound to all nearby players will play, with 0 being disabled and 1 being enabled"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".notify_with_sound","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Should glow ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .should_glow ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"If a Mob Captain's silhouette should show through blocks, with 0 being disabled and 1 being enabled"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".should_glow","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Beam on spawn ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .beam_on_spawn ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"If Mob Captains should create a particle beam when spawning that shows their location for about 1 second, with 1 being turned on and 0 it being turned off"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".beam_on_spawn","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Weight common ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .weight_common ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"Weight for a Mob Captain being of common rarity"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".weight_common","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Weight uncommon ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .weight_uncommon ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"Weight for a Mob Captain being of uncommon rarity"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".weight_uncommon","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Weight rare ","clickEvent":{"action":"suggest_command","value":"/scoreboard players set .weight_rare ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"Weight for a Mob Captain being of rare rarity"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".weight_rare","objective":"ps-mob.config"},"color":"red"},{"text":"\n"},{"text":"Weight legendary ","clickEvent":{"action":"suggest_legendary","value":"/scoreboard players set .weight_legendary ps-mob.config "},"hoverEvent":{"action":"show_text","contents":"Weight for a Mob Captain being of legendary rarity"}},{"text":"[0 | 1]","color":"gray"},{"text":" "},{"score":{"name":".weight_legendary","objective":"ps-mob.config"},"color":"red"},{"text":"\n"}] at position 4644: ...t": "\n"}]<--[HERE]
	at hb.a(SourceFile:76) ~[server-1.20.4.jar:?]
	at aht.a(SourceFile:83) ~[server-1.20.4.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
	

The datapack broke and I cant use the commands to change the values of the mob captains and they dont work properly as well.

**Comment by PuckiSilver** [comment] 2023-12-29 06:47
That’s very strange, I'll look into it when I get the time, thanks for the details

**Comment by donschriefer** [comment] 2024-01-04 15:53
I have the same issue, running dedicated Fabric 1.20.4:

**Closed** 2024-01-10 13:36 UTC
Labels: bug
