### ISSUE TITLE
This mod breaks mob spawner

### ISSUE THREAD

**Issue by gguy825** [ps-dps/MobCaptains#33] opened 2024-03-06 03:49 UTC
Just added this mod but seems to affect mob spawns for me in a way that breaks mob spawn farms. I have one currently setup but nothing spawns when this mod is active.

**Comment by PuckiSilver** [comment] 2024-03-06 05:42
Does it break all spawning from mob spawners or just that no Mob Captains spawn from mob spawners?
Because the later one is correct.

If it's breaking more spawns, not just Mob Captain spawns, then please tell me more info like - other mods, Minecraft version, is this on a server or singleplayer, what mod loader are you using, does the pack work at all for you?

**Comment by gguy825** [comment] 2024-03-06 06:25
For version im on 1.20.1. i have a ton of mods but none that affect the mobs like this one does. this and Enderman Overhaul are the only mob based mods I have installed and this issue only started after installing this mod. Yea its breaking spawning from the mod spawner specifically. Mob captains still spawn out in the world, its just once I get to the mob spawner, no regular mobs spawn. they usually start spawning in once I get near my chest. even standing inside the box when its closed they still don't spawn for some reason. This is the design I'm using. https://www.youtube.com/watch?v=30JWnYnduH0

**Comment by PuckiSilver** [comment] 2024-03-06 06:31
Mob Captains doesn’t mess with spawns in any way, it just elects some mobs to turn into captains. If no mobs spawn at all, I don’t know how Mob Captains could be causing that..

Also the thing in the pack affecting Captain spawns in farms isn’t even implemented in the older 1.20.1 version of the pack.

The next step would be to try it out in an otherwise vanilla setting to see it Mob Captains is actually at fault or it’s only in combination with a different mod.

**Comment by PuckiSilver** [comment] 2024-03-11 13:30
Any updates on this? I can not reproduce this in vanilla minecraft (with just the pack).
If not, I'll close this as 'Invalid'

**Comment by gguy825** [comment] 2024-03-11 17:49
No i haven't tried to test it any further with the mod installed. Its still a ton of fun using it on its own so I've just been turning it on and off when I want to use the mob spawner but i still haven't found the conflicting mod. I forgot i didn't post my mod list, these are the current ones installed. https://i.imgur.com/DXb6rD9.png

**Comment by PuckiSilver** [comment] 2024-03-21 23:33
These are a lot of mods, it’s most likely some incompatibility. Nothing in the pack touches actual spawning mechanics.

You can try setting the block area config to 0, that is the only thing I can think of, that mods could change that could lead to such a behavior.

Closing this as invalid for now, as it seems to be an incompatibility with some mod and not a problem with the pack itself.

**Closed by PuckiSilver** 2024-03-21 23:33 UTC
Labels: invalid
